BOT_NAME = 'vnw'
BOT_VERSION = '1.0.5'

SPIDER_MODULES = ['vnw.spiders']
NEWSPIDER_MODULE = 'vnw.spiders'
USER_AGENT = '%s/%s' % (BOT_NAME, BOT_VERSION)

VIETNAMWORK_USERNAME = ''
VIETNAMWORK_PASSWORD = ''
